server:
  servlet:
    context-path: /
  connection-timeout: 6000000
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost/userdb
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
